---
- name: Check if CSF Present
  stat:
    path: /etc/csf/version.txt
  register: csf_check

- name: Ensure IP Whitelist File Exists
  copy:
    src: '{{ ip_whitelist_file }}'
    dest: '{{ csf_whitelist_file }}'
    owner: root
    group: root
    mode: '0600'
  when: csf_check.stat.exists

- name: Ensure IP Whitelist File Include in /etc/csf/csf.allow
  lineinfile:
    path: /etc/csf/csf.allow
    regexp: '^Include {{ csf_whitelist_file }}'
    line: 'Include {{ csf_whitelist_file }}'
    insertafter: '^# add it to csf.ignore'
    state: present
  when: csf_check.stat.exists
  notify: Restart CSF